// All player-visible strings (localization-ready).
window.STR = {
  title: "DAO'S FIELD",
  subtitle: "Human World I",
  loading: "Entering Human World I…",
  enter: "Enter the Valley",
  chooseOrigin: "Choose your origin",
  races: { human:"Human", beast:"Beast", spirit_beast:"Spirit Beast", monster:"Monster" },
  hintDesktop: "WASD / Arrows move · drag look · Shift run · click / Space attack · E observe",
  hintTouch: "Left stick move · right side look · tap attack · tap marker to observe",
  audioOn: "♪ Music", audioOff: "♪ Muted",
  cityName: "Yunhe Water Town",
  poi: {
    spirit_vein: { name:"Spirit Vein", lore:"Qi wells up from the earth here. Sects wage wars over veins like this — the lifeblood of cultivation." },
    stele:       { name:"Ancient Stele", lore:"Weathered characters record a cultivator who ascended ten thousand years ago. Their name is lost; their Dao endures." },
    shrine:      { name:"Cloud Shrine", lore:"Travelers leave offerings before the long road up the mountain. Above the clouds lie Human Worlds II through IX — and beyond." },
    village_elder:  { name:"Village Elder", lore:"The Elder of Yunhe Water Town has watched a thousand cultivators pass through his gate. He knows which roads lead upward — and which lead only to graves." },
    alchemist:      { name:"Alchemist", lore:"Her furnace never cools. Spirit-herbs dry in the rafters and pills rattle in ceramic jars. A mortal body can only be tempered so far before it needs her elixirs." },
    blacksmith:     { name:"Blacksmith", lore:"Soot blackens the beams of the forge. He folds star-metal a thousand times; a blade from his hand can bite through a beast's qi-hardened hide." },
    merchant:       { name:"Merchant", lore:"Silk, talismans, spirit-stones, rumors — all have a price at his stall. Coin moves the mortal world as surely as qi moves the immortal." },
    sect_recruiter: { name:"Sect Recruiter", lore:"She waits in the riverside pavilion, weighing every passerby's root and aura. Impress her, and the long climb to the mountain sects may begin here." },
  },
  observe: "observe",
  vsNote: "Cinematic open-world vertical slice · one valley · not the full MMO",
};
